# Generated by Django 4.2.6 on 2023-10-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='plec',
            field=models.IntegerField(choices=[(1, 'Kobieta'), (2, 'Mezczyzna'), (3, 'Inne')], default=3),
        ),
    ]
